default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: ember_book_store_development

test:
  <<: *default
  database: ember_book_store_test

production:
  <<: *default
  database: ember_book_store_production
